version: '3'
services:
  app:
    image: app
    build:
      context: .
    ports:
      - 5001:5000
    networks:
      - my-network
    volumes:
      - ./app:/app  # This line mounts your local 'app' directory into the container
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: flask_app_user
      MYSQL_PASSWORD: flask_app_password
    networks:
      - my-network

networks:
  my-network: